export const MAJORS = [
  "Business Administration",
  "Computer Science",
  "Engineering",
  "Medicine",
  "Law",
  "Education",
  "Arts and Design",
  "Social Sciences",
  "Natural Sciences",
  "Mathematics",
  "Psychology",
  "Economics",
  "Architecture",
  "Nursing",
  "Pharmacy",
  "Dentistry",
  "Veterinary Science",
  "Agriculture",
  "Environmental Science",
  "Information Technology",
];

export const SPECIALIZATIONS = {
  "Business Administration": [
    "Finance",
    "Marketing",
    "Human Resources",
    "International Business",
    "Entrepreneurship",
    "Supply Chain Management",
    "Business Analytics",
  ],
  "Computer Science": [
    "Software Engineering",
    "Artificial Intelligence",
    "Data Science",
    "Cybersecurity",
    "Cloud Computing",
    "Web Development",
    "Mobile Development",
  ],
  "Engineering": [
    "Mechanical Engineering",
    "Electrical Engineering",
    "Civil Engineering",
    "Chemical Engineering",
    "Aerospace Engineering",
    "Industrial Engineering",
    "Software Engineering",
  ],
  "Medicine": [
    "General Medicine",
    "Surgery",
    "Pediatrics",
    "Cardiology",
    "Neurology",
    "Oncology",
    "Psychiatry",
  ],
  // Add more specializations for other majors
};

export const VISA_TYPES = [
  "Student Visa",
  "Work Visa",
  "Tourist Visa",
  "Business Visa",
  "Dependent Visa",
  "Permanent Resident Visa",
  "Transit Visa",
  "Working Holiday Visa",
  "Research Visa",
  "Exchange Visitor Visa",
]; 